Workflow Changes

diff --git a/.github/workflows/redeploy-containers.yaml b/.github/workflows/redeploy-containers.yaml
--- a/.github/workflows/redeploy-containers.yaml
+++ b/.github/workflows/redeploy-containers.yaml
@@ -29,7 +29,6 @@ jobs:
       env:
         CHANGED_CONTAINERS: ${{ steps.changed-containers.outputs.CHANGED_CONTAINERS }}
       run: |
-        SUCCESSFUL_CONTAINERS=''
         FAILED_CONTAINERS=''
         IFS=',' read -ra FILES <<< "$CHANGED_CONTAINERS"
         for file in "${FILES[@]}"; do
@@ -38,46 +37,32 @@ jobs:
           cp -f "$file" /home/kyle/docker-files/"$file"
           echo "Updating $service_name..."
           if DEPLOY_OUTPUT=$(docker compose -f /home/kyle/docker-files/"$file" up -d --force-recreate 2>&1); then
-            SUCCESSFUL_CONTAINERS+=$service_name", "
+            curl \
+            -u ${{ secrets.NTFY_LOGIN }} \
+            -H "Title: Container Redeployed" \
+            -H "Tags: tada" \
+            -H "Content-Type: text/plain" \
+            -d "$service_name was redeployed successfully." \
+            ${{ secrets.NTFY_URL }}
             echo "$service_name Deployed Successfully"
           else
-            FAILED_CONTAINERS+=$service_name", "
+            curl \
+            -u ${{ secrets.NTFY_LOGIN }} \
+            -H "Title: Redeployment Failed" \
+            -H "Tags: warning" \
+            -H "Content-Type: text/plain" \
+            -d "$service_name encountered an error while redeploying.
+            Error: $(echo "$DEPLOY_OUTPUT" | cut -d':' -f2- | sed 's/^[ \t]*//;s/[ \t]*$//')" \
+            ${{ secrets.NTFY_URL }}
             echo "$service_name Failed To Deploy"
+            FAILED_CONTAINERS+=1
+            echo "FAILED_CONTAINERS=$FAILED_CONTAINERS" >> "$GITHUB_OUTPUT"
           fi
         done
-        echo "Successful Containers: $SUCCESSFUL_CONTAINERS"
-        echo "SUCCESSFULY_DEPLOYED=$(echo "$SUCCESSFUL_CONTAINERS" | tr '\n' ',' | sed 's/,$//')" >> $GITHUB_OUTPUT
-        echo "Failed Containers: $FAILED_CONTAINERS"
-        echo "FAILED_DEPLOYED=$(echo "$FAILED_CONTAINERS" | tr '\n' ',' | sed 's/,$//')" >> $GITHUB_OUTPUT
 
-    - name: Send Notification on Fail
+    - name: Exit Job On Failed Deployment
       env:
-        SUCCESSFULY_DEPLOYED: ${{ steps.deploy-containers.outputs.SUCCESSFULY_DEPLOYED }}
-        FAILED_DEPLOYED: ${{ steps.deploy-containers.outputs.FAILED_DEPLOYED }}
+        FAILED_CONTAINERS ${{ steps.deploy-containers.outputs.FAILED_DEPLOYED }}
       if: ${{ steps.deploy-containers.outputs.FAILED_DEPLOYED != '' }}
       run: |
-        curl \
-        -u ${{ secrets.NTFY_LOGIN }} \
-        -H "Title: Redeployment Failed" \
-        -H "Tags: warning" \
-        -H "Content-Type: text/plain" \
-        -d "$FAILED_DEPLOYED encountered an error while redeploying." \
-        ${{ secrets.NTFY_URL }}
-
-        # curl \
-        # -u ${{ secrets.NTFY_LOGIN }} \
-        # -H "Title: Container Redeployed" \
-        # -H "Tags: tada" \
-        # -H "Content-Type: text/plain" \
-        # -d "$service_name was redeployed successfully." \
-        # ${{ secrets.NTFY_URL }}
-
-        # curl \
-        # -u ${{ secrets.NTFY_LOGIN }} \
-        # -H "Title: Redeployment Failed" \
-        # -H "Tags: warning" \
-        # -H "Content-Type: text/plain" \
-        # -d "$service_name encountered an error while redeploying.
-        # Error: $(echo "$DEPLOY_OUTPUT" | cut -d':' -f2- | sed 's/^[ \t]*//;s/[ \t]*$//')" \
-        # ${{ secrets.NTFY_URL }}
-        # echo "FAILED_CONTAINERS=" >> "$GITHUB_OUTPUT"
+        exit 1
